server:
  port: 8003
spring:
  application:
    name: service-hystrix-8003

feign:
  hystrix:
    enabled: true
eureka:
  instance:
    hostname: 127.0.0.1
    port: 8000
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
