server:
  port: 8002
spring:
  application:
    name: service-provider-two-8004
eureka:
  instance:
    hostname: 127.0.0.1
    port: 8000
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
